# Generated by Django 3.0.7 on 2020-07-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palfullthrottle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activityperiod',
            table='activity_period',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
